---
###########################
# Install php from source #
###########################
- include_tasks: Common/common_php_install_with_git.yml
  when: install_type == "git"

- include_tasks: Common/common_php_configure.yml

- include_tasks: Common/common_configure_opcache.yml

- include_tasks: Common/common_configure_pcntl.yml